[package]
name = "util"
version = "0.0.1"
authors = ["liuzhishan <liuzhishan01@gmail.com>"]
edition = "2021"
license = "MIT OR Apache-2.0"
readme = "README.md"
description = "util for sniper."

[dependencies]
log = "0.4"
env_logger = "0.7"
anyhow = "1.0"
api = { path = "../api" }
